# frozen_string_literal: false

source 'https://rubygems.org'

ruby '~> 2.7.2'

gem 'airrecord'
gem 'dotenv'
gem 'erubis'
gem 'pry'
gem 'pry-byebug'
gem 'sinatra', '~>1.4.7'
gem 'sinatra-contrib'
gem 'pg'

gem "minitest"
gem "minitest-reporters"
gem "rack-test"
gem "simplecov"

group :production do
  gem 'puma'
end
