source "https://rubygems.org"

ruby '~> 2.7.2'

gem "dotenv"
gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem "airrecord"
gem "pry"
gem "pry-byebug"

group :production do
  gem "puma"
end
